---

title: Indexmod blockchainpedia
timezone: UTC
description: Indexmod is a fashion and art blockchainpedia

show_sidebar: false
show_downloads: false
show_title: false
show_description: false
git_branch: master

theme: jekyll-theme-minimal

include: ['.htaccess']
<<<<<<< HEAD
exclude:
=======

exclude: 
>>>>>>> 13527c8e18e7550f2d2ad9c0f91a1ae0066f744e
- style.css
- redirects.json
- sitemap.xml
- robots.txt
- feed.xml
<<<<<<< HEAD
=======

>>>>>>> 13527c8e18e7550f2d2ad9c0f91a1ae0066f744e

use_github_wiki: false
use_prose_io: true
custom_head: false
custom_sidebar: false
custom_footer: false

prose:
  rooturl: 'https://indexmod.ga'
  siteurl: 'https://indexmod.ga'
  relativeLinks: 'https://prose.github.io/starter/links.jsonp'
  media: '/images'

  ignore:
    - index.md
    - _config.yml
    - /_layouts
    - /_includes
    - 404.md
    - README.md
    - feed.xml
    - sitemap.xml
    - robots.txt
    - redirects.json
